1월25일 문제
cheekykorkind/solveFridayProblem pull request #2
Opened 2019-01-29 11:39 UTC by cheekykorkind

### 문제를 풀자

![1](https://user-images.githubusercontent.com/22050468/51905907-e95af700-2405-11e9-9d39-c35a4e59037b.jpg)
![2](https://user-images.githubusercontent.com/22050468/51905908-e9f38d80-2405-11e9-97d9-39e332ddd5e3.jpg)

2019-02-09 13:31 UTC, crane93 commented on gamble/exec.bat
> +java -cp target/gamble-1.0-SNAPSHOT.jar com.jiho.app.App
이게 뭔가요?

2019-02-09 13:31 UTC, crane93 commented on gamble/src/main/java/com/jiho/app/App.java
> +        new NumberChecker(n).start();
오오

2019-02-09 13:33 UTC, yuriKIM-i3 requested changes
안되요

2019-02-09 13:33 UTC, yuriKIM-i3 approved these changes
LGTM!

2019-02-09 13:34 UTC, cheekykorkind commented on gamble/src/main/java/com/jiho/app/App.java
> +        new NumberChecker(n).start();
멋있지
🔥

2019-02-12 11:41 UTC, merged

2019-02-13 04:46 UTC, crane93 commented
설명없이 코드만 볼려고 하니까 뭐가 뭔지 모르겠네요 ㅠ

2019-02-13 11:29 UTC, cheekykorkind reviewed
설명 붙였습니다

2019-02-13 11:29 UTC, cheekykorkind commented on gamble/src/main/java/com/jiho/model/Data.java
> +	public static int first = 10;
어디서든 볼수있는 전역변수로 숫자 3개를 선언

2019-02-13 11:29 UTC, cheekykorkind commented on gamble/src/main/java/com/jiho/task/NumberChecker.java
> +public class NumberChecker extends Thread
숫자 3개가 일치하는지 확인하는 역할 담당하는 쓰레드

2019-02-13 11:29 UTC, cheekykorkind commented on gamble/src/main/java/com/jiho/task/NumberGenerater.java
> +public class NumberGenerater extends Thread
숫자 3개를 0.2초 간격으로 하나씩 갱신하는 쓰레드

2019-02-13 11:29 UTC, cheekykorkind commented on gamble/src/main/java/com/jiho/view/MainFrame.java
> +public class MainFrame
미사용. 신경쓰지 않아도 됨.

2019-02-13 11:29 UTC, cheekykorkind commented on gamble/src/test/java/com/jiho/app/AppTest.java
> +public class AppTest
미사용 신경쓰지 않아도 됨

2019-02-13 11:29 UTC, cheekykorkind commented on gamble/pom.xml
> +<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
환경설정 파일. 신경쓰지 않아도 됨.

2019-02-13 12:04 UTC, crane93 commented on gamble/src/main/java/com/jiho/task/NumberGenerater.java
> +                    Data.first = (int) (Math.random() * 10 % 5);
Data클래스말고 
그냥 여기서 int first라고 변수 선언하면 어떻게 되나요?

2019-02-13 12:12 UTC, cheekykorkind commented on gamble/src/main/java/com/jiho/task/NumberGenerater.java
> +                    Data.first = (int) (Math.random() * 10 % 5);
NumberGenerater클래스 내부에서만 사용하는 변수가 되서
NumberChecker클래스에서 확인할 수 없습니다.